sunday = Day.create(name: "sunday")
monday = Day.create(name: "monday")
tuesday = Day.create(name: "tuesday")
wednesday = Day.create(name: "wednesday")
thursday = Day.create(name: "thursday")
friday = Day.create(name: "friday")
saturday = Day.create(name: "saturday")
